money_data/urls.py
from django.urls import path

from . import views

app_name = 'money_data'
urlpatterns = [
    path('', views.index, name='index'),
    path('moneylogs/', views.money, name='moneylogs'),
    path('edit_log/<int:log_id>/', views.edit_log, name="edit_log"),
    path('delete/<int:log_id>/', views.delete_log, name="delete_log"),
    path('data/', views.line_chart, name='data'),
]

pokertracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('money_data.urls', namespace='money_data')),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', 
        auth_views.LoginView.as_view(template_name='users/login.html'), 
        name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
]

money_data/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class MoneyLog(models.Model):
    """A class for logging money that the user has made"""
    money_made = models.FloatField(help_text="")
    date_added = models.DateField(auto_now_add=False)
    money_info = models.TextField(default="", blank=True)
    anonymous = models.BooleanField(default=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        """return a string rep of the model"""
        return str(self.money_made)

users/models.py
from django.db import models

# Create your models here.

money_data/forms.py
from django import forms
from datetime import date

from .models import MoneyLog

class MoneyForm(forms.ModelForm):
    class Meta:
        model=MoneyLog
        fields=['money_made', 'money_info', 'date_added']
        labels={'money_made': 'Money Made', 'money_info': 'Extra Info', 'date_added': 'Date'}
        widgets = {
            'money_made': forms.NumberInput(attrs={
                'placeholder': 'Amount', 
                'class': 'form-input',
                'id': 'money_made-input',
            }),
            'money_info': forms.Textarea(attrs={
                'class': 'form-input',
                'id': 'money_info-input'
                }),
            'date_added': forms.DateInput(attrs={
                'class': 'form-input', 
                'type':'date',
                'id': 'date_added-input',
                'value': date.today()
                })
        }

money_data/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import MoneyLog
from .forms import MoneyForm
from django.http import HttpResponseRedirect, Http404
from datetime import date
import plotly.express as px
import plotly
import pandas
from datetime import datetime
import math
# Create your views here.

def index(request):
    return render(request, 'money_data/index.html')

@login_required
def money(request):
    moneylogs = MoneyLog.objects.filter(owner=request.user).order_by('-date_added')

    # render and process add form
    if request.method != 'POST':
        form = MoneyForm({'date_added': date.today()})
    else:
        form = MoneyForm(data=request.POST)
        if form.is_valid():
            new_log = form.save(commit=False)
            new_log.owner = request.user
            new_log.save()
            return HttpResponseRedirect(reverse('money_data:moneylogs'))

    # show total loss/profit
    money_sum = 0
    for i in MoneyLog.objects.filter(owner=request.user).all():
        money_sum += i.money_made


    formatted_date = date.today().strftime("%Y-%m-%d")
    print(formatted_date)
    context = {'moneylogs': moneylogs, 'form': form, 'money_sum': money_sum, 'date_value': formatted_date}
    return render(request, 'money_data/moneylogs.html', context)

def delete_log(request, log_id):
    log = MoneyLog.objects.get(id=log_id)
    if log.owner != request.user:
        raise Http404
    log.delete()
    return HttpResponseRedirect(reverse('money_data:moneylogs'))

def edit_log(request, log_id):
    log = MoneyLog.objects.get(id=log_id)
    if log.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = MoneyForm(instance=log)
    else:
        form = MoneyForm(instance=log, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('money_data:moneylogs'))

    context = { 'log': log, 'form': form }
    return render(request, 'money_data/edit_log.html', context)

@login_required
def line_chart(request):
    moneylogs = MoneyLog.objects.filter(owner=request.user).order_by('date_added')
    # nb_element = len(moneylogs)
    # xdata = range(nb_element)
    xdata = [i for i in range(len(moneylogs) + 1)]
    # # xdata = [int(time.mktime(datetime.datetime.combine(i.date_added,  my_time).timetuple()) * 1000) for i in moneylogs]
    ydata = []
    for i in range(len(moneylogs) + 1):
        total_sum = 0
        for j in moneylogs[:i]:
            total_sum += j.money_made
        ydata.append(total_sum)

    
    df = pandas.DataFrame(dict(x=xdata, y=ydata))
    fig = px.line(
        df, 
        x="x", 
        y="y", 
        markers=True, 
        labels=dict(x="session #", y="total money"), 
        title='Earnings',
    )
    fig.update_layout(
        xaxis=dict(
            tickmode='linear',
        ),
        plot_bgcolor='rgba(0, 0, 0, 0)',
        paper_bgcolor='rgba(255, 255, 255)',
        margin={'l': 0},
    )
    fig.update_xaxes(gridwidth=.5, gridcolor="LightGrey")
    fig.update_yaxes(gridwidth=.5, gridcolor="LightGrey")
    graph_div = plotly.offline.plot(
        fig, 
        auto_open = False,
        output_type="div", 
        config={'responsive': False, 'staticPlot': True},
    )

    # session average
    money_list = list([i.money_made for i in moneylogs])
    if len(money_list) != 0:
        average_per_session = round(sum(money_list)/len(money_list),2 )
    else: 
        average_per_session = 0

    # total money made
    total_money_made = round(sum(money_list), 2)

    # amount made this month
    currentMonth = datetime.now().month
    logs_this_month = list()
    for i in moneylogs:
        if i.date_added.month == currentMonth:
            logs_this_month.append(i)
    money_this_month = [i.money_made for i in logs_this_month]
    money_this_month = round(sum(money_this_month), 2)

    data = {'$/session': average_per_session, '$ total': total_money_made, '$ total this month': money_this_month}

    context = {'graph_div': graph_div, 'data': data}

    return render(request, 'money_data/data.html', context)

from django import template

register = template.Library()

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse

# Create your views here.

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('money_data:moneylogs'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

money_data/templates/money_data/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'money_data/style.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&display=swap" rel="stylesheet">
        <script src="https://kit.fontawesome.com/a38fe3c449.js" crossorigin="anonymous"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <div class="navbar" id="navbar">
            <ul>
                {% if not user.is_authenticated %}
                    <li><a href="{% url 'money_data:index' %}">Home</a></li>
                {% endif %}
                <li><a href="{% url 'money_data:moneylogs' %}">Logs</a></li>
            </ul>
            <ul>
            {% if user.is_authenticated %}
                    <li id="dropdown-li">
                        <div class="dropdown">
                            <button>Hello, {{user.username }}
                                <i class="fa-solid fa-caret-down"></i>
                            </button>
                            <div class="dropdown-content">
                                <a href="{% url 'money_data:data' %}">Data</a>
                                <a href="{% url 'users:logout' %}">Logout</a>
                            </div>
                        </div>
                    </li>
                <!-- <li><a href="{% url 'users:logout' %}">logout</a></li> -->
            {% else %}
            <li><a href="{% url 'users:login' %}">Login</a></li>
            <li><a href="{% url 'users:register' %}">Register</a></li>
            {% endif %}
            </ul>
        </div>
        {% block content %}{% endblock content %}
        <script type="text/javascript" src="{% static 'money_data/script.js' %}"></script>
    </body>
</html>

money_data/templates/money_data/data.html
{% extends 'money_data/base.html' %}
{% block content %}
{% load mathfilters %}

<div class="main">
    <div style="width: 100%;">
        <div id="statistics">
            {% for key, value in data.items %}
                {% if value > 0 %}
                    <div class="stat green-text">
                        <h1>{{ key }}</h1>
                        <p>${{ value }}</p>
                    </div>
                {% elif 0 > value %}
                    <div class="stat red-text">
                        <h1>{{ key }}</h1>
                        <p>-${{ value|abs }}</p>
                    </div>
                {% else %}
                    <div class="stat">
                        <h1>{{ key }}</h1>
                        <p>${{ value }}</p>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <div style="width: 100%;">
        <div  class="graph-div">
            {{ graph_div|safe }}
        </div>
    </div>
</div>
{% endblock content %}
<!--TODO: 
    - make responsive grid design for the session data
    - figure out sizing for the graph
    - style login/register/edit log page (shouldn't be redundant)

    -Deploy!
-->

money_data/templates/money_data/edit_log.html
{% extends 'money_data/base.html' %}
{% load static %}

{% block content %}
<div class="main" style="height: 100%;">
    <div class="center" style="height: 80%;">
        <div class="form-element" style="height: 28em; text-align: center;">
        <h1 style="text-align: center; padding: .7em;">edit log</h1>

    <form action="{% url 'money_data:edit_log' log.id %}" id="edit-log-form" method="post">
        {% csrf_token %}
        {{form}}
        <div style="margin-top: 1em;"></div>
        <button class="form-confirm-button confirm-button">confirm changes</button>
    </form>
</div>
</div>
</div>
{% endblock content %}

money_data/templates/money_data/index.html
{% extends "money_data/base.html" %}

{% block content %}
<div class="main" style="height: 70%;">
    <div style="height: 100%; display: flex; align-items: center;">
        <div class="homepage">
            <div class="headers">
                <h1>Become a pro</h1>
                <div class="subheader">
                    <h2>track your poker earnings and see if you have what it takes to be one of the greats </h2>
                </div>
            </div>
            <div style="padding: 2em;"></div>
            <div class="login-buttons">
                <a href="{% url 'users:login' %}">
                    <button class="login-register-button">
                        login
                    </button>
                </a>
                <a href="{% url 'users:register' %}">
                    <button href="{% url 'users:login' %}" class="login-register-button">
                        register
                    </button>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

money_data/templates/money_data/moneylogs.html
{% extends "money_data/base.html" %}
{% load static %}

{% block content %}
<div class="main" id="main">
    <div id="top">
        <div class="form-element" id="form-element">
            <form action="{% url 'money_data:moneylogs' %}" method="post">
                {% csrf_token %}
                <div id="inner-form">
                    <div class="side-to-side-input">
                        <label for="money_made-input">Money Made</label>
                        <ul class="errorlist"><li>This field is required.</li></ul>
                        <input type="number" name="money_made" placeholder="Amount" class="form-input" id="money_made-input" step="any" required="">
                        <label for="date_added-input">Date</label>
                        <input type="date" name="date_added" value="{{date_value}}" class="form-input" id="date_added-input" required="">
                    </div>
                    <div>
                        <label for="money_info-input">Extra Info (optional)</label>
                        <textarea name="money_info" cols="40" rows="10" class="form-input" id="money_info-input"></textarea>
                    </div>
                </div>
                <button class="confirm-button form-confirm-button" id="" name="submit">New Log</button>
            </form>
        </div>
        <!-- <button id="buttonElement" onclick="showForm()">new form</button> -->
    </div>
    <div id="outter-table-element">
        <div id="table-element">
            <table>
                    <tr>
                        <th>date</th>
                        <th>amount</th>
                        <th>notes</th>
                        <th>edit</th>
                    </tr>
                    {% for m in moneylogs %}
                        <tr>
                            <td>{{m.date_added|date:'M d, Y' }}</td>
                                <td>${{m}}</td>
                            <!-- {{m.money_info|linebreaks}} for future use -->
                                <td>{{m.money_info}}</td>
                                <td>
                                    <button
                                        onclick="location.href='{% url 'money_data:edit_log' m.id %}'"
                                        class="icon-button">
                                        <img
                                            class="icon" 
                                            src="{% static 'money_data/assets/icons8-edit-24.png' %}" 
                                            width="15" />
                                    </button>
                                
                                    <button 
                                        class="icon-button"
                                        type="submit"
                                        name="del_button"
                                        onclick="
                                        sessionStorage.setItem('id', {{m.id}});
                                        trashCanPopUp();
                                        "
                                    >
                                        <img 
                                            id="del-button"
                                            class="icon" 
                                            width="15" 
                                            src="{% static 'money_data/assets/icons8-trash-30.png' %}"
                                            />
                                    </button>
                                </td>
                        {% empty %}
                        {% endfor %}
                        </tr>
            </table>
        </div>
    </div>
    <p id="bottom-table">Net profit/loss: ${{ money_sum }}</p>

</div>
<div id="popup">
    <div>
        <h2>Are you sure?</h2>
    </div>
    <div>
        <p>Deleting this item is an action that cannot be undone</p>
    </div>
    <div class="buttons">
        <div class="confirm-button" id="yes-button">
            <a href="#" onclick="trashCanPopUp()
            var id = sessionStorage.getItem('id');
            var url = `{% url 'money_data:delete_log' log_id=1234 %}`.replace(/1234/, id)
            location.href = url;"
            >yes</a>
        </div>
        <div class="confirm-button" id="no-button">
            <a href="#" onclick="trashCanPopUp()">no</a>
        </div>
    </div>
</div>
<script src="{% static 'money_data/script.js' %}"></script>
{% endblock content %}

users/templates/users/login.html
{% extends 'money_data/base.html' %}
{% load static %}

{% block content %}
    <div class="center">
        <div class="form-element login-register">
            <h1>Welcome back</h1>
            <form method="post" action="{% url 'users:login' %}">
                {% csrf_token %}
                <input class="my-username-class form-input login-input" type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" class="my-username-class" required="" id="id_username" placeholder="username"></p>
                <input class="my-password-class form-input login-input" type="password" name="password" autocomplete="current-password" class="my-password-class" required="" id="id_password" placeholder="password"></p>
                <input type="hidden" name="next" value="{% url 'money_data:moneylogs' %}" />
                <button class="confirm-button form-confirm-button" name="submit">log in</button>
            </form>
            <p>Don't have an account? <a href="{% url 'users:register' %}">register</a></p>
        </div>
        {% if form.errors %}
            <p class="login-errors">your username and password didn't match</p>
        {% endif %}
    </div>

{% endblock content %}

users/templates/users/register.html
{% extends 'money_data/base.html' %}
{% load static %}

{% block content %}
    <div class="center">

        <div class="form-element login-register register">
            <h1>Registration</h1>
            <form method="post" action="{% url 'users:register' %}">
                {% csrf_token %}
                <input class="my-username-class form-input login-input" type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username" placeholder="username"></p>
                <input class="my-username-class form-input login-input" type="password" name="password1" autocomplete="new-password" required="" id="id_password1" placeholder="password"></p>
                <input class="my-username-class form-input login-input" type="password" name="password2" autocomplete="new-password" required="" id="id_password2" placeholder="confirm password"></p>
                <button class="confirm-button form-confirm-button" name="submit">Register</button>
                <input type="hidden" name="next" value="{% url 'money_data:index' %}">
            </form>

        <p>Already have an account? <a href="{% url 'users:login' %}">log in</a></p>

        </div>
        {% if form.errors %}
                <p class="registration-errors">Registration invalid. </p>
        {% endif %}
    </div>

{% endblock content %}